# Generated by Django 5.0 on 2024-04-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='manager',
            new_name='customer',
        ),
    ]
