# Generated by Django 5.0 on 2024-04-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_rename_manager_house_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='customer',
            new_name='manager',
        ),
    ]
