# Generated by Django 5.0 on 2024-04-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='house',
            new_name='product',
        ),
    ]
